# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qm5UvBXwoe8fI88JoD2rHd_h6n-sBlV7
"""

import numpy as np
import matplotlib.pyplot as plt

def lanczos(A, k, u1=None):
    """
    Metode Lanczos stabil untuk matriks simetris A (n x n)
    """
    n = A.shape[0]

    # vektor awal
    if u1 is None:
        u = np.random.rand(n)
    else:
        u = u1.copy()

    u = u / np.linalg.norm(u)

    U = np.zeros((n, k))
    alpha = np.zeros(k)
    beta = np.zeros(k-1)

    U[:, 0] = u

    for j in range(k):
        v = A @ U[:, j]

        if j > 0:
            v -= beta[j-1] * U[:, j-1]

        alpha[j] = np.dot(U[:, j], v)
        v -= alpha[j] * U[:, j]

        # 👉 FULL REORTHOGONALIZATION (PERBAIKAN UTAMA)
        for i in range(j):
            v -= np.dot(U[:, i], v) * U[:, i]

        if j < k - 1:
            beta[j] = np.linalg.norm(v)
            if beta[j] < 1e-12:
                break
            U[:, j+1] = v / beta[j]

    # matriks tridiagonal
    T = np.diag(alpha)
    for j in range(k-1):
        T[j, j+1] = beta[j]
        T[j+1, j] = beta[j]

    return T

def lanczos_convergence(A, kmax):
    true_eigs = np.linalg.eigvalsh(A)
    lambda_min_true = float(true_eigs[0])
    lambda_max_true = float(true_eigs[-1])

    approx_min = []
    approx_max = []

    for k in range(1, kmax + 1):
        T = lanczos(A, k)
        eig_T = np.linalg.eigvalsh(T)

        approx_min.append(float(eig_T[0]))
        approx_max.append(float(eig_T[-1]))

    return approx_min, approx_max, lambda_min_true, lambda_max_true

#===============================================================================
# Masukkan Elemen Matriks
#===============================================================================
A = np.array([
    [4, 1, 0],
    [1, 3, 1],
    [0, 1, 2]
], dtype=float)

kmax = A.shape[0]

approx_min, approx_max, lam_min, lam_max = lanczos_convergence(A, kmax)

print("Eigenvalue sebenarnya:")
print(np.linalg.eigvalsh(A))

print("\nKonvergensi λ_min:")
for k, val in enumerate(approx_min, 1):
    print(f"k={k:2d} → λ_min ≈ {val:.6f}")

print("\nKonvergensi λ_max:")
for k, val in enumerate(approx_max, 1):
    print(f"k={k:2d} → λ_max ≈ {val:.6f}")

plt.figure()
plt.plot(range(1, kmax+1), approx_min, marker='o', label='Hampiran λ_min')
plt.plot(range(1, kmax+1), approx_max, marker='s', label='Hampiran λ_max')
plt.axhline(lam_min, linestyle='--', label='λ_min sebenarnya')
plt.axhline(lam_max, linestyle='--', label='λ_max sebenarnya')
plt.xlabel('Iterasi Lanczos (k)')
plt.ylabel('Nilai Eigen')
plt.title('Konvergensi Eigenvalue Ekstrem – Metode Lanczos')
plt.legend()
plt.show()